version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
  client:
    build: ./client
    command: npm run serve
    volumes:
      - ./client/:/usr/src/client/
    ports:
      - 8080:8080
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/server/
      - ./client/:/usr/src/client/
    ports:
      - 8000:8000
    depends_on:
      - client
      - db

volumes:
  postgres_data: